package mimetype

// builtin 是跨平台稳定的扩展名 → 类型表,优先于 mime.TypeByExtension(后者在
// Unix 读系统 mime.types、Windows 读注册表,同一次上传在不同机器上结果可能不同)。
//
// 取值以 mime-db(jshttp, MIT;nginx / mime-types 等的事实数据源)与 IANA 注册表
// 为准。规则:人可读的文本内容优先取 text/*(浏览器内联显示而非下载),代码类多为
// 事实标准 text/x-*;IANA 已注册的非 text/* 值(application/json、application/sql、
// application/toml、application/graphql…;json 有浏览器原生查看器)保持注册值不动。
var builtin = map[string]string{
	// —— 网页 / 文本 ——
	".html":     "text/html; charset=utf-8",
	".htm":      "text/html; charset=utf-8",
	".xhtml":    "application/xhtml+xml",
	".css":      "text/css; charset=utf-8",
	".js":       "text/javascript; charset=utf-8",
	".mjs":      "text/javascript; charset=utf-8",
	".cjs":      "text/javascript; charset=utf-8",
	".txt":      "text/plain; charset=utf-8",
	".log":      "text/plain; charset=utf-8",
	".ini":      "text/plain; charset=utf-8",
	".cfg":      "text/plain; charset=utf-8",
	".conf":     "text/plain; charset=utf-8",
	".env":      "text/plain; charset=utf-8",
	".md":       "text/markdown; charset=utf-8",
	".markdown": "text/markdown; charset=utf-8",
	".rst":      "text/x-rst; charset=utf-8",
	".csv":      "text/csv; charset=utf-8",
	".tsv":      "text/tab-separated-values; charset=utf-8",
	".xml":      "text/xml; charset=utf-8",
	".json":     "application/json",
	".jsonl":    "application/x-ndjson",
	".ndjson":   "application/x-ndjson",
	// .yaml/.yml 取事实标准的 text/yaml(浏览器内联显示);RFC 9512 注册的
	// application/yaml 会被浏览器当下载处理,与"能渲染"的目标相反。
	".yaml": "text/yaml; charset=utf-8",
	".yml":  "text/yaml; charset=utf-8",
	".toml": "application/toml",
	".vtt":  "text/vtt; charset=utf-8",
	".srt":  "application/x-subrip",
	".ics":  "text/calendar; charset=utf-8",
	".vcf":  "text/vcard; charset=utf-8",

	// —— 代码 ——
	// .ts 同名冲突:TypeScript 与 MPEG-TS 都用它。这里取代码语义(视频请用 .mts/.m2ts)。
	".ts":      "text/typescript; charset=utf-8",
	".jsx":     "text/jsx; charset=utf-8",
	".tsx":     "text/tsx; charset=utf-8",
	".py":      "text/x-python; charset=utf-8",
	".pyi":     "text/x-python; charset=utf-8",
	".ipynb":   "application/x-ipynb+json",
	".go":      "text/x-go; charset=utf-8",
	".rs":      "text/x-rust; charset=utf-8",
	".c":       "text/x-c; charset=utf-8",
	".h":       "text/x-c; charset=utf-8",
	".cc":      "text/x-c++; charset=utf-8",
	".cpp":     "text/x-c++; charset=utf-8",
	".cxx":     "text/x-c++; charset=utf-8",
	".hh":      "text/x-c++; charset=utf-8",
	".hpp":     "text/x-c++; charset=utf-8",
	".java":    "text/x-java-source; charset=utf-8",
	".kt":      "text/x-kotlin; charset=utf-8",
	".kts":     "text/x-kotlin; charset=utf-8",
	".scala":   "text/x-scala; charset=utf-8",
	".rb":      "text/x-ruby; charset=utf-8",
	".php":     "text/x-php; charset=utf-8",
	".pl":      "text/x-perl; charset=utf-8",
	".lua":     "text/x-lua; charset=utf-8",
	".r":       "text/x-r; charset=utf-8",
	".swift":   "text/x-swift; charset=utf-8",
	".dart":    "application/vnd.dart",
	".ex":      "text/x-elixir; charset=utf-8",
	".exs":     "text/x-elixir; charset=utf-8",
	".erl":     "text/x-erlang; charset=utf-8",
	".hrl":     "text/x-erlang; charset=utf-8",
	".clj":     "text/x-clojure; charset=utf-8",
	".cljs":    "text/x-clojure; charset=utf-8",
	".hs":      "text/x-haskell; charset=utf-8",
	".ml":      "text/x-ocaml; charset=utf-8",
	".mli":     "text/x-ocaml; charset=utf-8",
	".groovy":  "text/x-groovy; charset=utf-8",
	".asm":     "text/x-asm; charset=utf-8",
	".vue":     "text/x-vue; charset=utf-8",
	".svelte":  "text/x-svelte; charset=utf-8",
	".proto":   "text/x-protobuf; charset=utf-8",
	".sh":      "text/x-sh; charset=utf-8",
	".bash":    "text/x-sh; charset=utf-8",
	".zsh":     "text/x-sh; charset=utf-8",
	".fish":    "text/x-sh; charset=utf-8",
	".ps1":     "text/x-powershell; charset=utf-8",
	".bat":     "text/plain; charset=utf-8",
	".cmd":     "text/plain; charset=utf-8",
	".sql":     "application/sql",
	".graphql": "application/graphql",

	// —— 图片 ——
	".jpg":  "image/jpeg",
	".jpeg": "image/jpeg",
	".png":  "image/png",
	".gif":  "image/gif",
	".webp": "image/webp",
	".svg":  "image/svg+xml",
	".svgz": "image/svg+xml",
	".bmp":  "image/bmp",
	".ico":  "image/vnd.microsoft.icon",
	".tif":  "image/tiff",
	".tiff": "image/tiff",
	".avif": "image/avif",
	".heic": "image/heic",
	".heif": "image/heif",
	".jxl":  "image/jxl",
	".apng": "image/apng",
	".psd":  "image/vnd.adobe.photoshop",

	// —— 视频 ——
	".mp4":  "video/mp4",
	".m4v":  "video/x-m4v",
	".mov":  "video/quicktime",
	".avi":  "video/x-msvideo",
	".mkv":  "video/x-matroska",
	".webm": "video/webm",
	".flv":  "video/x-flv",
	".wmv":  "video/x-ms-wmv",
	".mpg":  "video/mpeg",
	".mpeg": "video/mpeg",
	".mpe":  "video/mpeg",
	".m2v":  "video/mpeg",
	".3gp":  "video/3gpp",
	".3g2":  "video/3gpp2",
	".ogv":  "video/ogg",
	".mts":  "video/mp2t",
	".m2ts": "video/mp2t",
	".mpd":  "application/dash+xml",
	".m3u8": "application/vnd.apple.mpegurl",
	".m3u":  "audio/x-mpegurl",

	// —— 音频 ——
	".mp3":  "audio/mpeg",
	".wav":  "audio/wav",
	".m4a":  "audio/mp4",
	".aac":  "audio/aac",
	".flac": "audio/flac",
	".ogg":  "audio/ogg",
	".oga":  "audio/ogg",
	".opus": "audio/opus",
	".wma":  "audio/x-ms-wma",
	".mid":  "audio/midi",
	".midi": "audio/midi",
	".aiff": "audio/aiff",
	".aif":  "audio/aiff",
	".amr":  "audio/amr",
	".ra":   "audio/x-realaudio",
	".caf":  "audio/x-caf",

	// —— 字体 ——
	".woff":  "font/woff",
	".woff2": "font/woff2",
	".ttf":   "font/ttf",
	".otf":   "font/otf",
	".ttc":   "font/collection",
	".eot":   "application/vnd.ms-fontobject",

	// —— 压缩包 ——
	".zip": "application/zip",
	".tar": "application/x-tar",
	".gz":  "application/gzip",
	".tgz": "application/gzip",
	".bz2": "application/x-bzip2",
	".xz":  "application/x-xz",
	".zst": "application/zstd",
	".7z":  "application/x-7z-compressed",
	".rar": "application/vnd.rar",
	".jar": "application/java-archive",
	".war": "application/java-archive",
	".apk": "application/vnd.android.package-archive",
	".dmg": "application/x-apple-diskimage",
	".iso": "application/x-iso9660-image",
	".deb": "application/vnd.debian.binary-package",
	".rpm": "application/x-redhat-package-manager",
	".cab": "application/vnd.ms-cab-compressed",

	// —— 文档 ——
	".pdf":     "application/pdf",
	".doc":     "application/msword",
	".docx":    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
	".xls":     "application/vnd.ms-excel",
	".xlsx":    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
	".ppt":     "application/vnd.ms-powerpoint",
	".pptx":    "application/vnd.openxmlformats-officedocument.presentationml.presentation",
	".odt":     "application/vnd.oasis.opendocument.text",
	".ods":     "application/vnd.oasis.opendocument.spreadsheet",
	".odp":     "application/vnd.oasis.opendocument.presentation",
	".rtf":     "application/rtf",
	".epub":    "application/epub+zip",
	".mobi":    "application/x-mobipocket-ebook",
	".tex":     "application/x-tex",
	".pages":   "application/vnd.apple.pages",
	".numbers": "application/vnd.apple.numbers",

	// —— 数据 / 其他 ——
	".wasm":        "application/wasm",
	".map":         "application/json",
	".webmanifest": "application/manifest+json",
	".sqlite":      "application/vnd.sqlite3",
	".sqlite3":     "application/vnd.sqlite3",
	".torrent":     "application/x-bittorrent",
}
